/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.abadier.enrolmentsystem;

import static edu.abadier.enrolmentsystem.Subjects.subjects;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ron.g.abadier
 */
public class AdminWindowSubjects extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindowSubjects
     */
    public AdminWindowSubjects() {
        initComponents();
        SetTableView();
        AddColumnListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        textUser = new javax.swing.JLabel();
        panelUsersList = new javax.swing.JPanel();
        headerUsersList = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        headerRegister = new javax.swing.JLabel();
        panelProfile = new javax.swing.JPanel();
        headerProfile = new javax.swing.JLabel();
        panelSubjects = new javax.swing.JPanel();
        headerSubjects = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        panelRegisterSubject = new javax.swing.JPanel();
        buttonRegister = new javax.swing.JButton();
        fieldSubjectName = new javax.swing.JTextField();
        fieldSubjectCode = new javax.swing.JTextField();
        headerSubjectTeacher = new javax.swing.JLabel();
        headerSubjectName = new javax.swing.JLabel();
        headerSubjectCode = new javax.swing.JLabel();
        headerRegisterSubject = new javax.swing.JLabel();
        fieldSubjectTeacher = new javax.swing.JTextField();
        panelSubjectList = new javax.swing.JPanel();
        buttonSearch = new javax.swing.JButton();
        scrollSubjectList = new javax.swing.JScrollPane();
        tableSubjectList = new javax.swing.JTable();
        buttonNewSubject = new javax.swing.JButton();
        headerSubjectTitle = new javax.swing.JLabel();
        fieldSubjectSearch = new javax.swing.JTextField();
        panelUpdateSubject = new javax.swing.JPanel();
        buttonUpdate = new javax.swing.JButton();
        fieldUpdateSubjectTeacher = new javax.swing.JTextField();
        fieldUpdateSubjectName = new javax.swing.JTextField();
        fieldUpdateSubjectCode = new javax.swing.JTextField();
        headerUpdateSubjectTeacher = new javax.swing.JLabel();
        headerUpdateSubjectName = new javax.swing.JLabel();
        headerUpdateSubjectCode = new javax.swing.JLabel();
        headerUpdateRegisterSubject = new javax.swing.JLabel();
        panelSubjectDelete = new javax.swing.JPanel();
        fieldDeleteSubjectCode = new javax.swing.JTextField();
        headerDeleteSubjectCode = new javax.swing.JLabel();
        headerDeleteSubject = new javax.swing.JLabel();
        buttonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        buttonLogout.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(null);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        textUser.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        textUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUser.setText("ADMINISTRATOR");
        textUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelUsersList.setBackground(new java.awt.Color(224, 224, 224));
        panelUsersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUsersListMouseClicked(evt);
            }
        });

        headerUsersList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUsersList.setText("Users List");

        javax.swing.GroupLayout panelUsersListLayout = new javax.swing.GroupLayout(panelUsersList);
        panelUsersList.setLayout(panelUsersListLayout);
        panelUsersListLayout.setHorizontalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerUsersList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersListLayout.setVerticalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersListLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerUsersList)
                .addContainerGap())
        );

        panelRegister.setBackground(new java.awt.Color(224, 224, 224));
        panelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegisterMouseClicked(evt);
            }
        });

        headerRegister.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegister.setText("Register");

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerRegister)
                .addContainerGap())
        );

        panelProfile.setBackground(new java.awt.Color(224, 224, 224));
        panelProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProfileMouseClicked(evt);
            }
        });

        headerProfile.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerProfile.setText("Profile");

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerProfile)
                .addContainerGap())
        );

        panelSubjects.setBackground(new java.awt.Color(224, 224, 224));
        panelSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSubjectsMouseClicked(evt);
            }
        });

        headerSubjects.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjects.setText("Subjects");

        javax.swing.GroupLayout panelSubjectsLayout = new javax.swing.GroupLayout(panelSubjects);
        panelSubjects.setLayout(panelSubjectsLayout);
        panelSubjectsLayout.setHorizontalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerSubjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubjectsLayout.setVerticalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerSubjects)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(panelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(textUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelRegisterSubject.setBackground(new java.awt.Color(255, 255, 255));

        buttonRegister.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        headerSubjectTeacher.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjectTeacher.setText("Subject Teacher");
        headerSubjectTeacher.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerSubjectName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjectName.setText("Subject Name");
        headerSubjectName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerSubjectCode.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjectCode.setText("Subject Code");
        headerSubjectCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerRegisterSubject.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerRegisterSubject.setText("SUBJECT REGISTER ");

        fieldSubjectTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSubjectTeacherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRegisterSubjectLayout = new javax.swing.GroupLayout(panelRegisterSubject);
        panelRegisterSubject.setLayout(panelRegisterSubjectLayout);
        panelRegisterSubjectLayout.setHorizontalGroup(
            panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterSubjectLayout.createSequentialGroup()
                .addGroup(panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fieldSubjectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelRegisterSubjectLayout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldSubjectName)
                                .addGroup(panelRegisterSubjectLayout.createSequentialGroup()
                                    .addGroup(panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelRegisterSubjectLayout.createSequentialGroup()
                                            .addComponent(headerSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fieldSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(headerSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(headerSubjectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(188, 188, 188))))
                        .addGroup(panelRegisterSubjectLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(headerRegisterSubject)
                            .addGap(131, 131, 131))))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterSubjectLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonRegister)
                .addGap(50, 50, 50))
        );
        panelRegisterSubjectLayout.setVerticalGroup(
            panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterSubjectLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerRegisterSubject)
                .addGap(18, 18, 18)
                .addGroup(panelRegisterSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerSubjectCode)
                    .addComponent(fieldSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerSubjectName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headerSubjectTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldSubjectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(buttonRegister)
                .addGap(67, 67, 67))
        );

        tabPane.addTab("Register", panelRegisterSubject);

        panelSubjectList.setBackground(new java.awt.Color(255, 255, 255));

        buttonSearch.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tableSubjectList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tableSubjectList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Subject", "Teacher"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSubjectList.getTableHeader().setReorderingAllowed(false);
        scrollSubjectList.setViewportView(tableSubjectList);
        if (tableSubjectList.getColumnModel().getColumnCount() > 0) {
            tableSubjectList.getColumnModel().getColumn(0).setResizable(false);
            tableSubjectList.getColumnModel().getColumn(1).setResizable(false);
            tableSubjectList.getColumnModel().getColumn(2).setResizable(false);
        }

        buttonNewSubject.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonNewSubject.setText("New Subject");
        buttonNewSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNewSubjectActionPerformed(evt);
            }
        });

        headerSubjectTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerSubjectTitle.setText("SUBJECT LIST");

        fieldSubjectSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSubjectSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSubjectListLayout = new javax.swing.GroupLayout(panelSubjectList);
        panelSubjectList.setLayout(panelSubjectListLayout);
        panelSubjectListLayout.setHorizontalGroup(
            panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectListLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSubjectListLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectListLayout.createSequentialGroup()
                                .addComponent(fieldSubjectSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonSearch))
                            .addComponent(scrollSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSubjectListLayout.createSequentialGroup()
                        .addComponent(headerSubjectTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonNewSubject)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelSubjectListLayout.setVerticalGroup(
            panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectListLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerSubjectTitle)
                    .addComponent(buttonNewSubject))
                .addGap(18, 18, 18)
                .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSearch)
                    .addComponent(fieldSubjectSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        tabPane.addTab("View", panelSubjectList);

        panelUpdateSubject.setBackground(new java.awt.Color(255, 255, 255));

        buttonUpdate.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonUpdate.setText("Update");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        fieldUpdateSubjectTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUpdateSubjectTeacherActionPerformed(evt);
            }
        });

        headerUpdateSubjectTeacher.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUpdateSubjectTeacher.setText("Subject Teacher");
        headerUpdateSubjectTeacher.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerUpdateSubjectName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUpdateSubjectName.setText("Subject Name");
        headerUpdateSubjectName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerUpdateSubjectCode.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUpdateSubjectCode.setText("Subject Code");
        headerUpdateSubjectCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerUpdateRegisterSubject.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerUpdateRegisterSubject.setText("SUBJECT PROFILE ");

        javax.swing.GroupLayout panelUpdateSubjectLayout = new javax.swing.GroupLayout(panelUpdateSubject);
        panelUpdateSubject.setLayout(panelUpdateSubjectLayout);
        panelUpdateSubjectLayout.setHorizontalGroup(
            panelUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateSubjectLayout.createSequentialGroup()
                .addGroup(panelUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateSubjectLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(headerUpdateRegisterSubject))
                    .addGroup(panelUpdateSubjectLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldUpdateSubjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addGroup(panelUpdateSubjectLayout.createSequentialGroup()
                                .addComponent(headerUpdateSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldUpdateSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(headerUpdateSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerUpdateSubjectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateSubjectLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(fieldUpdateSubjectTeacher))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateSubjectLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonUpdate)))
                .addGap(50, 50, 50))
        );
        panelUpdateSubjectLayout.setVerticalGroup(
            panelUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateSubjectLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerUpdateRegisterSubject)
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerUpdateSubjectCode)
                    .addComponent(fieldUpdateSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerUpdateSubjectName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldUpdateSubjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(headerUpdateSubjectTeacher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldUpdateSubjectTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(buttonUpdate)
                .addGap(67, 67, 67))
        );

        tabPane.addTab("Update", panelUpdateSubject);

        panelSubjectDelete.setBackground(new java.awt.Color(255, 255, 255));

        headerDeleteSubjectCode.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerDeleteSubjectCode.setText("Subject Code");
        headerDeleteSubjectCode.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerDeleteSubject.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerDeleteSubject.setText("SUBJECT DELETE ");

        buttonDelete.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonDelete.setText("Delete");
        buttonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDeleteMouseClicked(evt);
            }
        });
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSubjectDeleteLayout = new javax.swing.GroupLayout(panelSubjectDelete);
        panelSubjectDelete.setLayout(panelSubjectDeleteLayout);
        panelSubjectDeleteLayout.setHorizontalGroup(
            panelSubjectDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectDeleteLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelSubjectDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSubjectDeleteLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(headerDeleteSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldDeleteSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(170, Short.MAX_VALUE))
                    .addGroup(panelSubjectDeleteLayout.createSequentialGroup()
                        .addComponent(headerDeleteSubject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonDelete)
                        .addGap(33, 33, 33))))
        );
        panelSubjectDeleteLayout.setVerticalGroup(
            panelSubjectDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectDeleteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelSubjectDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerDeleteSubject)
                    .addComponent(buttonDelete))
                .addGap(18, 18, 18)
                .addGroup(panelSubjectDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerDeleteSubjectCode)
                    .addComponent(fieldDeleteSubjectCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );

        tabPane.addTab("Delete", panelSubjectDelete);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.show();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void panelUsersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsersListMouseClicked
        this.setVisible(false);
        AdminWindowUserList awul = new AdminWindowUserList();
        awul.show();
        awul.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelUsersListMouseClicked

    private void panelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegisterMouseClicked
        this.setVisible(false);
        AdminWindowRegisterUser awru = new AdminWindowRegisterUser();
        awru.show();
        awru.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelRegisterMouseClicked

    private void panelProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProfileMouseClicked
        this.setVisible(false);
        AdminWindowProfile awp = new AdminWindowProfile();
        awp.show();
        awp.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelProfileMouseClicked

    private void panelSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSubjectsMouseClicked
        this.setVisible(false);
        AdminWindowSubjects aws = new AdminWindowSubjects();
        aws.show();
        aws.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelSubjectsMouseClicked

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
        String code = fieldSubjectCode.getText();
        String subjectName = fieldSubjectName.getText();
        String subjectTeacher = fieldSubjectTeacher.getText();
        
        Subject newSubject = new Subject(code, subjectName, subjectTeacher);
        Subjects.subjects.add(newSubject);
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void fieldSubjectTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSubjectTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSubjectTeacherActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void fieldUpdateSubjectTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUpdateSubjectTeacherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUpdateSubjectTeacherActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void fieldSubjectSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSubjectSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSubjectSearchActionPerformed

    private void buttonNewSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNewSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonNewSubjectActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        String subjectCode = fieldDeleteSubjectCode.getText();
        
        for(int i = 0; i < subjects.size(); i++){
            if(subjects.get(i).getSubjectCode().equals(subjectCode)){
                subjects.remove(i);
            }
        }
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void buttonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDeleteMouseClicked
        String subjectCode = fieldDeleteSubjectCode.getText();
        
        if (subjectCode == ""){
            javax.swing.JFrame failedDelete = new javax.swing.JFrame();
            javax.swing.JOptionPane.showMessageDialog(failedDelete, "You have a blank field! Please fill up all fields.");
        } else {
            for(int i = 0; i < subjects.size(); i++){
                if(subjects.get(i).getSubjectCode().equals(subjectCode)){
                    subjects.remove(i);
                }
            }
            javax.swing.JFrame successfulDelete = new javax.swing.JFrame();
            javax.swing.JOptionPane.showMessageDialog(successfulDelete, "Subject successfully deleted!");
        }
    }//GEN-LAST:event_buttonDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindowSubjects().setVisible(true);
            }
        });
    }
    
        void SetTableView() {
        DefaultTableModel subjectList = (DefaultTableModel) tableSubjectList.getModel();
        subjectList.setRowCount(0);
        
        for (int i = 0; i < subjects.size(); i++){
            String code = subjects.get(i).getSubjectCode();
            String name = subjects.get(i).getSubjectName();
            String teacher = subjects.get(i).getSubjectTeacher();
            
            Object[] row = {code, name, teacher};
            subjectList.addRow(row);
        }
    }
    
    void AddColumnListener() {
        JTableHeader header = tableSubjectList.getTableHeader();
        header.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                int columnIndex = header.columnAtPoint(e.getPoint());
                System.out.println("Column " + columnIndex + " is clicked.");
                
                switch(columnIndex){
                    case 0 -> {
                        subjects = Subjects.sortCode(subjects, descending);
                        descending = !descending;
                    }
                    case 1 -> {
                        subjects = Subjects.sortName(subjects, descending);
                        descending = !descending;
                    }
                    case 2 -> {
                        subjects = Subjects.sortTeacher(subjects, descending);
                        descending = !descending;
                    }
                }
                SetTableView();
            }
        });
    }

    private boolean descending = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonNewSubject;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JTextField fieldDeleteSubjectCode;
    private javax.swing.JTextField fieldSubjectCode;
    private javax.swing.JTextField fieldSubjectName;
    private javax.swing.JTextField fieldSubjectSearch;
    private javax.swing.JTextField fieldSubjectTeacher;
    private javax.swing.JTextField fieldUpdateSubjectCode;
    private javax.swing.JTextField fieldUpdateSubjectName;
    private javax.swing.JTextField fieldUpdateSubjectTeacher;
    private javax.swing.JLabel headerDeleteSubject;
    private javax.swing.JLabel headerDeleteSubjectCode;
    private javax.swing.JLabel headerProfile;
    private javax.swing.JLabel headerRegister;
    private javax.swing.JLabel headerRegisterSubject;
    private javax.swing.JLabel headerSubjectCode;
    private javax.swing.JLabel headerSubjectName;
    private javax.swing.JLabel headerSubjectTeacher;
    private javax.swing.JLabel headerSubjectTitle;
    private javax.swing.JLabel headerSubjects;
    private javax.swing.JLabel headerUpdateRegisterSubject;
    private javax.swing.JLabel headerUpdateSubjectCode;
    private javax.swing.JLabel headerUpdateSubjectName;
    private javax.swing.JLabel headerUpdateSubjectTeacher;
    private javax.swing.JLabel headerUsersList;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JPanel panelRegisterSubject;
    private javax.swing.JPanel panelSubjectDelete;
    private javax.swing.JPanel panelSubjectList;
    private javax.swing.JPanel panelSubjects;
    private javax.swing.JPanel panelUpdateSubject;
    private javax.swing.JPanel panelUsersList;
    private javax.swing.JScrollPane scrollSubjectList;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tableSubjectList;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
