/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.abadier.enrolmentsystem;

import java.util.Date;

/**
 *
 * @author ron.g.abadier
 */
public class AdminWindowRegisterUser extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindowRegisterUser
     */
    public AdminWindowRegisterUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        headerAdministrator = new javax.swing.JLabel();
        panelUsersList = new javax.swing.JPanel();
        headerUsersList = new javax.swing.JLabel();
        panelRegisterUser = new javax.swing.JPanel();
        headerRegisterUser = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        panelProfile = new javax.swing.JPanel();
        headerProfile = new javax.swing.JLabel();
        panelSubjects = new javax.swing.JPanel();
        headerSubjects = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        panelRegisterAdmin = new javax.swing.JPanel();
        headerAdminYear = new javax.swing.JLabel();
        headerAdminGender = new javax.swing.JLabel();
        comboAdminMonth = new javax.swing.JComboBox<>();
        headerAdminBirthdate = new javax.swing.JLabel();
        headerAdminMonth = new javax.swing.JLabel();
        buttonAdminBackToUserList = new javax.swing.JButton();
        headerAdminMiddleName = new javax.swing.JLabel();
        headerAdminLastName = new javax.swing.JLabel();
        fieldAdminMiddleName = new javax.swing.JTextField();
        buttonAdminRegister = new javax.swing.JButton();
        fieldAdminLastName = new javax.swing.JTextField();
        fieldAdminFirstName = new javax.swing.JTextField();
        fieldAdminIdNum = new javax.swing.JTextField();
        headerAdminJobTitle = new javax.swing.JLabel();
        headerAdminFirstName = new javax.swing.JLabel();
        comboAdminYear = new javax.swing.JComboBox<>();
        headerAdminIdNum = new javax.swing.JLabel();
        headerAdminTitle = new javax.swing.JLabel();
        comboAdminDate = new javax.swing.JComboBox<>();
        comboAdminGender = new javax.swing.JComboBox<>();
        headerAdminDate = new javax.swing.JLabel();
        fieldAdminJobTitle = new javax.swing.JTextField();
        panelRegisterStudent = new javax.swing.JPanel();
        buttonStudentRegister = new javax.swing.JButton();
        buttonStudentBackToUserList = new javax.swing.JButton();
        headerStudentTitle = new javax.swing.JLabel();
        headerStudentSection = new javax.swing.JLabel();
        comboStudentSection = new javax.swing.JComboBox<>();
        headerStudentMiddleName = new javax.swing.JLabel();
        headerStudentIdNum = new javax.swing.JLabel();
        comboStudentYear = new javax.swing.JComboBox<>();
        headerStudentBirthdate = new javax.swing.JLabel();
        comboStudentMonth = new javax.swing.JComboBox<>();
        fieldStudentIdNum = new javax.swing.JTextField();
        headerStudentGender = new javax.swing.JLabel();
        headerStudentYear = new javax.swing.JLabel();
        fieldStudentFirstName = new javax.swing.JTextField();
        fieldStudentLastName = new javax.swing.JTextField();
        headerStudentDate = new javax.swing.JLabel();
        comboStudentGender = new javax.swing.JComboBox<>();
        fieldStudentMiddleName1 = new javax.swing.JTextField();
        comboStudentDate = new javax.swing.JComboBox<>();
        headerStudentLastName = new javax.swing.JLabel();
        headerStudentMonth = new javax.swing.JLabel();
        headerStudentFirstName = new javax.swing.JLabel();
        panelRegisterTeacher = new javax.swing.JPanel();
        headerTeacherYear = new javax.swing.JLabel();
        headerTeacherGender = new javax.swing.JLabel();
        comboTeacherMonth = new javax.swing.JComboBox<>();
        headerTeacherBirthdate = new javax.swing.JLabel();
        headerTeacherMonth = new javax.swing.JLabel();
        buttonTeacherBackToUserList = new javax.swing.JButton();
        headerTeacherMiddleName = new javax.swing.JLabel();
        headerTeacherLastName = new javax.swing.JLabel();
        fieldTeacherMiddleName = new javax.swing.JTextField();
        buttonTeacherRegister = new javax.swing.JButton();
        fieldTeacherLastName = new javax.swing.JTextField();
        fieldTeacherFirstName = new javax.swing.JTextField();
        fieldTeacherIdNum = new javax.swing.JTextField();
        headerTeacherJobTitle = new javax.swing.JLabel();
        headerTeacherFirstName = new javax.swing.JLabel();
        comboTeacherYear = new javax.swing.JComboBox<>();
        headerTeacherIdNum = new javax.swing.JLabel();
        headerTeacherTitle = new javax.swing.JLabel();
        comboTeacherDate = new javax.swing.JComboBox<>();
        comboTeacherGender = new javax.swing.JComboBox<>();
        headerTeacherDate = new javax.swing.JLabel();
        fieldTeacherJobTitle = new javax.swing.JTextField();
        headerTeacherSubject = new javax.swing.JLabel();
        fieldTeacherSubject = new javax.swing.JTextField();
        panelRegisterRegistrar = new javax.swing.JPanel();
        headerRegistrarYear = new javax.swing.JLabel();
        headerRegistrarGender = new javax.swing.JLabel();
        comboRegistrarMonth = new javax.swing.JComboBox<>();
        headerRegistrarBirthdate = new javax.swing.JLabel();
        headerRegistrarMonth = new javax.swing.JLabel();
        buttonRegistrarBackToUserList = new javax.swing.JButton();
        headerRegistrarMiddleName = new javax.swing.JLabel();
        headerRegistrarLastName = new javax.swing.JLabel();
        fieldRegistrarMiddleName = new javax.swing.JTextField();
        buttonRegistrarRegister = new javax.swing.JButton();
        fieldRegistrarLastName = new javax.swing.JTextField();
        fieldRegistrarFirstName = new javax.swing.JTextField();
        fieldRegistrarIdNum = new javax.swing.JTextField();
        headerRegistrarJobTitle = new javax.swing.JLabel();
        headerRegistrarFirstName = new javax.swing.JLabel();
        comboRegistrarYear = new javax.swing.JComboBox<>();
        headerRegistrarIdNum = new javax.swing.JLabel();
        headerRegistrarTitle = new javax.swing.JLabel();
        comboRegistrarDate = new javax.swing.JComboBox<>();
        comboRegistrarGender = new javax.swing.JComboBox<>();
        headerRegistrarDate = new javax.swing.JLabel();
        fieldRegistrarJobTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        headerAdministrator.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerAdministrator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerAdministrator.setText("ADMINISTRATOR");
        headerAdministrator.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelUsersList.setBackground(new java.awt.Color(224, 224, 224));
        panelUsersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUsersListMouseClicked(evt);
            }
        });

        headerUsersList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUsersList.setText("Users List");

        javax.swing.GroupLayout panelUsersListLayout = new javax.swing.GroupLayout(panelUsersList);
        panelUsersList.setLayout(panelUsersListLayout);
        panelUsersListLayout.setHorizontalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerUsersList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersListLayout.setVerticalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersListLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerUsersList)
                .addContainerGap())
        );

        panelRegisterUser.setBackground(new java.awt.Color(224, 224, 224));
        panelRegisterUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegisterUserMouseClicked(evt);
            }
        });

        headerRegisterUser.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegisterUser.setText(" Register");

        javax.swing.GroupLayout panelRegisterUserLayout = new javax.swing.GroupLayout(panelRegisterUser);
        panelRegisterUser.setLayout(panelRegisterUserLayout);
        panelRegisterUserLayout.setHorizontalGroup(
            panelRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterUserLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerRegisterUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegisterUserLayout.setVerticalGroup(
            panelRegisterUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterUserLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerRegisterUser)
                .addContainerGap())
        );

        buttonLogout.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(null);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        panelProfile.setBackground(new java.awt.Color(224, 224, 224));
        panelProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProfileMouseClicked(evt);
            }
        });

        headerProfile.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerProfile.setText("Profile");

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerProfile)
                .addContainerGap())
        );

        panelSubjects.setBackground(new java.awt.Color(224, 224, 224));
        panelSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSubjectsMouseClicked(evt);
            }
        });

        headerSubjects.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjects.setText("Subjects");

        javax.swing.GroupLayout panelSubjectsLayout = new javax.swing.GroupLayout(panelSubjects);
        panelSubjects.setLayout(panelSubjectsLayout);
        panelSubjectsLayout.setHorizontalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerSubjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubjectsLayout.setVerticalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerSubjects)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(panelUsersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelRegisterUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(headerAdministrator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegisterUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelRegisterAdmin.setBackground(new java.awt.Color(255, 255, 255));

        headerAdminYear.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerAdminYear.setText("YYYY");

        headerAdminGender.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminGender.setText("Gender");
        headerAdminGender.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboAdminMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        headerAdminBirthdate.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminBirthdate.setText("Birthdate");
        headerAdminBirthdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminMonth.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerAdminMonth.setText("MM");

        buttonAdminBackToUserList.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonAdminBackToUserList.setText("Back");
        buttonAdminBackToUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminBackToUserListActionPerformed(evt);
            }
        });

        headerAdminMiddleName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminMiddleName.setText("Middle name");
        headerAdminMiddleName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminLastName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminLastName.setText("Last name");
        headerAdminLastName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        buttonAdminRegister.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonAdminRegister.setText("Register");
        buttonAdminRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminRegisterActionPerformed(evt);
            }
        });

        headerAdminJobTitle.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminJobTitle.setText("Title");
        headerAdminJobTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminFirstName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminFirstName.setText("First name");
        headerAdminFirstName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboAdminYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        headerAdminIdNum.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminIdNum.setText("ID number");
        headerAdminIdNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerAdminTitle.setText("ADMINISTRATOR REGISTER ");

        comboAdminDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboAdminGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        comboAdminGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminGenderActionPerformed(evt);
            }
        });

        headerAdminDate.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerAdminDate.setText("DD");

        javax.swing.GroupLayout panelRegisterAdminLayout = new javax.swing.GroupLayout(panelRegisterAdmin);
        panelRegisterAdmin.setLayout(panelRegisterAdminLayout);
        panelRegisterAdminLayout.setHorizontalGroup(
            panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                                .addComponent(headerAdminIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldAdminIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(headerAdminGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboAdminGender, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterAdminLayout.createSequentialGroup()
                                    .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerAdminMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAdminMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerAdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(headerAdminBirthdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterAdminLayout.createSequentialGroup()
                                    .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(headerAdminJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerAdminMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldAdminJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                                            .addComponent(comboAdminMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(headerAdminDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(comboAdminDate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(headerAdminYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboAdminYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                                .addComponent(headerAdminTitle)
                                .addGap(131, 131, 131))
                            .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                                .addComponent(buttonAdminBackToUserList)
                                .addGap(185, 185, 185)
                                .addComponent(buttonAdminRegister)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelRegisterAdminLayout.setVerticalGroup(
            panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterAdminLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerAdminTitle)
                .addGap(18, 18, 18)
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminIdNum)
                    .addComponent(fieldAdminIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerAdminGender)
                    .addComponent(comboAdminGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminFirstName)
                    .addComponent(headerAdminLastName)
                    .addComponent(headerAdminMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAdminMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerAdminBirthdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminMonth)
                    .addComponent(comboAdminMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerAdminDate)
                    .addComponent(comboAdminDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerAdminYear)
                    .addComponent(comboAdminYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminJobTitle)
                    .addComponent(fieldAdminJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegisterAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdminRegister)
                    .addComponent(buttonAdminBackToUserList))
                .addGap(63, 63, 63))
        );

        tabPane.addTab("Admin", panelRegisterAdmin);

        panelRegisterStudent.setBackground(new java.awt.Color(255, 255, 255));

        buttonStudentRegister.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonStudentRegister.setText("Register");
        buttonStudentRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentRegisterActionPerformed(evt);
            }
        });

        buttonStudentBackToUserList.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonStudentBackToUserList.setText("Back");
        buttonStudentBackToUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentBackToUserListActionPerformed(evt);
            }
        });

        headerStudentTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerStudentTitle.setText("STUDENT REGISTER ");

        headerStudentSection.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentSection.setText("Section");
        headerStudentSection.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboStudentSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Python", "Hue", "Unity", "Pattern", "Vision", "Symmetry", "Java", "Balance", "Max", "Maya", "Rhythm", "Harmony" }));
        comboStudentSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStudentSectionActionPerformed(evt);
            }
        });

        headerStudentMiddleName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentMiddleName.setText("Middle name");
        headerStudentMiddleName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerStudentIdNum.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentIdNum.setText("ID number");
        headerStudentIdNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboStudentYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        headerStudentBirthdate.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentBirthdate.setText("Birthdate");
        headerStudentBirthdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboStudentMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        headerStudentGender.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentGender.setText("Gender");
        headerStudentGender.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerStudentYear.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerStudentYear.setText("YYYY");

        headerStudentDate.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerStudentDate.setText("DD");

        comboStudentGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        comboStudentGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStudentGenderActionPerformed(evt);
            }
        });

        comboStudentDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        headerStudentLastName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentLastName.setText("Last name");
        headerStudentLastName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerStudentMonth.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerStudentMonth.setText("MM");

        headerStudentFirstName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerStudentFirstName.setText("First name");
        headerStudentFirstName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelRegisterStudentLayout = new javax.swing.GroupLayout(panelRegisterStudent);
        panelRegisterStudent.setLayout(panelRegisterStudentLayout);
        panelRegisterStudentLayout.setHorizontalGroup(
            panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                                .addComponent(headerStudentTitle)
                                .addGap(195, 195, 195))
                            .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                                .addComponent(buttonStudentBackToUserList)
                                .addGap(185, 185, 185)
                                .addComponent(buttonStudentRegister))))
                    .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                                .addComponent(headerStudentMonth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStudentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headerStudentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboStudentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headerStudentYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboStudentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(headerStudentBirthdate, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                                        .addComponent(headerStudentIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldStudentIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(headerStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(comboStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterStudentLayout.createSequentialGroup()
                                            .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(headerStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(12, 12, 12)
                                            .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(headerStudentMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldStudentMiddleName1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(headerStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                                        .addComponent(headerStudentSection, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboStudentSection, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
        );
        panelRegisterStudentLayout.setVerticalGroup(
            panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterStudentLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerStudentTitle)
                .addGap(18, 18, 18)
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerStudentIdNum)
                    .addComponent(fieldStudentIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerStudentGender)
                    .addComponent(comboStudentGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerStudentFirstName)
                    .addComponent(headerStudentLastName)
                    .addComponent(headerStudentMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldStudentFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStudentLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldStudentMiddleName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerStudentBirthdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerStudentMonth)
                    .addComponent(comboStudentMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerStudentDate)
                    .addComponent(comboStudentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerStudentYear)
                    .addComponent(comboStudentYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerStudentSection)
                    .addComponent(comboStudentSection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegisterStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStudentRegister)
                    .addComponent(buttonStudentBackToUserList))
                .addGap(63, 63, 63))
        );

        tabPane.addTab("Student", panelRegisterStudent);

        panelRegisterTeacher.setBackground(new java.awt.Color(255, 255, 255));

        headerTeacherYear.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerTeacherYear.setText("YYYY");

        headerTeacherGender.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherGender.setText("Gender");
        headerTeacherGender.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboTeacherMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        headerTeacherBirthdate.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherBirthdate.setText("Birthdate");
        headerTeacherBirthdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerTeacherMonth.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerTeacherMonth.setText("MM");

        buttonTeacherBackToUserList.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonTeacherBackToUserList.setText("Back");
        buttonTeacherBackToUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeacherBackToUserListActionPerformed(evt);
            }
        });

        headerTeacherMiddleName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherMiddleName.setText("Middle name");
        headerTeacherMiddleName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerTeacherLastName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherLastName.setText("Last name");
        headerTeacherLastName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        buttonTeacherRegister.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonTeacherRegister.setText("Register");
        buttonTeacherRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTeacherRegisterActionPerformed(evt);
            }
        });

        headerTeacherJobTitle.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherJobTitle.setText("Title");
        headerTeacherJobTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerTeacherFirstName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherFirstName.setText("First name");
        headerTeacherFirstName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboTeacherYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        headerTeacherIdNum.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherIdNum.setText("ID number");
        headerTeacherIdNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerTeacherTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerTeacherTitle.setText("TEACHER REGISTER ");

        comboTeacherDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboTeacherGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        comboTeacherGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTeacherGenderActionPerformed(evt);
            }
        });

        headerTeacherDate.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerTeacherDate.setText("DD");

        headerTeacherSubject.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerTeacherSubject.setText("Subject");
        headerTeacherSubject.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout panelRegisterTeacherLayout = new javax.swing.GroupLayout(panelRegisterTeacher);
        panelRegisterTeacher.setLayout(panelRegisterTeacherLayout);
        panelRegisterTeacherLayout.setHorizontalGroup(
            panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                        .addComponent(headerTeacherIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTeacherIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(headerTeacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(comboTeacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterTeacherLayout.createSequentialGroup()
                            .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(headerTeacherFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldTeacherFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(12, 12, 12)
                            .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(headerTeacherMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldTeacherMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(headerTeacherLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldTeacherLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(headerTeacherBirthdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterTeacherLayout.createSequentialGroup()
                            .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                                    .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(headerTeacherJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerTeacherMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboTeacherMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(headerTeacherDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(fieldTeacherJobTitle))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                                    .addComponent(headerTeacherSubject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(71, 71, 71))
                                .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                                    .addComponent(comboTeacherDate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(headerTeacherYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(comboTeacherYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(fieldTeacherSubject)))))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterTeacherLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonTeacherBackToUserList)
                .addGap(185, 185, 185)
                .addComponent(buttonTeacherRegister)
                .addGap(43, 43, 43))
            .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(headerTeacherTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegisterTeacherLayout.setVerticalGroup(
            panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerTeacherTitle)
                .addGap(18, 18, 18)
                .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerTeacherIdNum)
                    .addComponent(fieldTeacherIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerTeacherGender)
                    .addComponent(comboTeacherGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerTeacherFirstName)
                    .addComponent(headerTeacherLastName)
                    .addComponent(headerTeacherMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTeacherFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTeacherLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTeacherMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerTeacherBirthdate)
                .addGap(6, 6, 6)
                .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                        .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(headerTeacherMonth)
                            .addComponent(comboTeacherMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerTeacherDate)
                            .addComponent(comboTeacherDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(headerTeacherYear)
                            .addComponent(comboTeacherYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(headerTeacherJobTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldTeacherJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldTeacherSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRegisterTeacherLayout.createSequentialGroup()
                        .addComponent(headerTeacherSubject)
                        .addGap(28, 28, 28)))
                .addGap(28, 28, 28)
                .addGroup(panelRegisterTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTeacherRegister)
                    .addComponent(buttonTeacherBackToUserList))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        tabPane.addTab("Teacher", panelRegisterTeacher);
        panelRegisterTeacher.getAccessibleContext().setAccessibleName("");

        panelRegisterRegistrar.setBackground(new java.awt.Color(255, 255, 255));

        headerRegistrarYear.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerRegistrarYear.setText("YYYY");

        headerRegistrarGender.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarGender.setText("Gender");
        headerRegistrarGender.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboRegistrarMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        headerRegistrarBirthdate.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarBirthdate.setText("Birthdate");
        headerRegistrarBirthdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerRegistrarMonth.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerRegistrarMonth.setText("MM");

        buttonRegistrarBackToUserList.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonRegistrarBackToUserList.setText("Back");
        buttonRegistrarBackToUserList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarBackToUserListActionPerformed(evt);
            }
        });

        headerRegistrarMiddleName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarMiddleName.setText("Middle name");
        headerRegistrarMiddleName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerRegistrarLastName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarLastName.setText("Last name");
        headerRegistrarLastName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        buttonRegistrarRegister.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonRegistrarRegister.setText("Register");
        buttonRegistrarRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarRegisterActionPerformed(evt);
            }
        });

        headerRegistrarJobTitle.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarJobTitle.setText("Title");
        headerRegistrarJobTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerRegistrarFirstName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarFirstName.setText("First name");
        headerRegistrarFirstName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboRegistrarYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        headerRegistrarIdNum.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegistrarIdNum.setText("ID number");
        headerRegistrarIdNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerRegistrarTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerRegistrarTitle.setText("ADMINISTRATOR REGISTER ");

        comboRegistrarDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboRegistrarGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        comboRegistrarGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRegistrarGenderActionPerformed(evt);
            }
        });

        headerRegistrarDate.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerRegistrarDate.setText("DD");

        javax.swing.GroupLayout panelRegisterRegistrarLayout = new javax.swing.GroupLayout(panelRegisterRegistrar);
        panelRegisterRegistrar.setLayout(panelRegisterRegistrarLayout);
        panelRegisterRegistrarLayout.setHorizontalGroup(
            panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                                .addComponent(headerRegistrarIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldRegistrarIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(headerRegistrarGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboRegistrarGender, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterRegistrarLayout.createSequentialGroup()
                                    .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerRegistrarFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldRegistrarFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerRegistrarMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldRegistrarMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerRegistrarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldRegistrarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(headerRegistrarBirthdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegisterRegistrarLayout.createSequentialGroup()
                                    .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(headerRegistrarJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerRegistrarMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldRegistrarJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                                            .addComponent(comboRegistrarMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(headerRegistrarDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(comboRegistrarDate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(headerRegistrarYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboRegistrarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                                .addComponent(headerRegistrarTitle)
                                .addGap(131, 131, 131))
                            .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                                .addComponent(buttonRegistrarBackToUserList)
                                .addGap(185, 185, 185)
                                .addComponent(buttonRegistrarRegister)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelRegisterRegistrarLayout.setVerticalGroup(
            panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterRegistrarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerRegistrarTitle)
                .addGap(18, 18, 18)
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerRegistrarIdNum)
                    .addComponent(fieldRegistrarIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerRegistrarGender)
                    .addComponent(comboRegistrarGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerRegistrarFirstName)
                    .addComponent(headerRegistrarLastName)
                    .addComponent(headerRegistrarMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRegistrarFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldRegistrarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldRegistrarMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerRegistrarBirthdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerRegistrarMonth)
                    .addComponent(comboRegistrarMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerRegistrarDate)
                    .addComponent(comboRegistrarDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerRegistrarYear)
                    .addComponent(comboRegistrarYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerRegistrarJobTitle)
                    .addComponent(fieldRegistrarJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegisterRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegistrarRegister)
                    .addComponent(buttonRegistrarBackToUserList))
                .addGap(63, 63, 63))
        );

        tabPane.addTab("Registrar", panelRegisterRegistrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelUsersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsersListMouseClicked
        this.setVisible(false);
        AdminWindowUserList awul = new AdminWindowUserList();
        awul.show();
        awul.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelUsersListMouseClicked

    private void panelRegisterUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegisterUserMouseClicked
        this.setVisible(false);
        AdminWindowRegisterUser awru = new AdminWindowRegisterUser();
        awru.show();
        awru.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelRegisterUserMouseClicked

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.show();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void buttonAdminBackToUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminBackToUserListActionPerformed
        // TODO add your handling code here:dsda
    }//GEN-LAST:event_buttonAdminBackToUserListActionPerformed

    private void buttonAdminRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminRegisterActionPerformed
        String idNum = fieldAdminIdNum.getText();
        
        int genderIndex = comboAdminGender.getSelectedIndex();
        Gender gender = Gender.values()[genderIndex];        
        
        String firstName = fieldAdminFirstName.getText();
        String middleName = fieldAdminMiddleName.getText();
        String lastName = fieldAdminLastName.getText();
        FullName fullName = new FullName(firstName, middleName, lastName);
        
        int birthMonth = comboAdminMonth.getSelectedIndex();
        int birthDate = comboAdminDate.getSelectedIndex() + 1;
        int birthYear = comboAdminYear.getSelectedIndex() + 80;
        Date birthdate = new Date(birthYear, birthMonth, birthDate);
        
        String jobTitle = fieldAdminJobTitle.getText();
        
        Administrator newAdmin = new Administrator(idNum, fullName, birthdate, gender, jobTitle);
        Accounts.admins.add(newAdmin);
    }//GEN-LAST:event_buttonAdminRegisterActionPerformed

    private void comboAdminGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdminGenderActionPerformed

    private void buttonStudentRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentRegisterActionPerformed
        String idNum = fieldStudentIdNum.getText();
        
        int genderIndex = comboStudentGender.getSelectedIndex();
        Gender gender = Gender.values()[genderIndex];        
        
        String firstName = fieldStudentFirstName.getText();
        String middleName = fieldStudentMiddleName1.getText();
        String lastName = fieldStudentLastName.getText();
        FullName fullName = new FullName(firstName, middleName, lastName);
        
        int birthMonth = comboStudentMonth.getSelectedIndex();
        int birthDate = comboStudentDate.getSelectedIndex() + 1;
        int birthYear = comboStudentYear.getSelectedIndex() + 80;
        Date birthdate = new Date(birthYear, birthMonth, birthDate);
        
        int sectionIndex = comboStudentSection.getSelectedIndex();
        Section section = Section.values()[sectionIndex];
        int yearLevel;
        if (sectionIndex == 0){
            yearLevel = 11;
        } else {
            yearLevel = (sectionIndex + 1) % 2 == 0? 11: 12;
        }

        Student newStudent = new Student(idNum, fullName, birthdate, gender, yearLevel, section);
        Accounts.students.add(newStudent);
    }//GEN-LAST:event_buttonStudentRegisterActionPerformed

    private void buttonStudentBackToUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentBackToUserListActionPerformed
        // TODO add your handling code here:dsda
    }//GEN-LAST:event_buttonStudentBackToUserListActionPerformed

    private void comboStudentSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStudentSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStudentSectionActionPerformed

    private void comboStudentGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStudentGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStudentGenderActionPerformed

    private void buttonTeacherBackToUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeacherBackToUserListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTeacherBackToUserListActionPerformed

    private void buttonTeacherRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTeacherRegisterActionPerformed
        String idNum = fieldTeacherIdNum.getText();
        
        int genderIndex = comboTeacherGender.getSelectedIndex();
        Gender gender = Gender.values()[genderIndex];        
        
        String firstName = fieldTeacherFirstName.getText();
        String middleName = fieldTeacherMiddleName.getText();
        String lastName = fieldTeacherLastName.getText();
        FullName fullName = new FullName(firstName, middleName, lastName);
        
        int birthMonth = comboTeacherMonth.getSelectedIndex();
        int birthDate = comboTeacherDate.getSelectedIndex() + 1;
        int birthYear = comboTeacherYear.getSelectedIndex() + 80;
        Date birthdate = new Date(birthYear, birthMonth, birthDate);
        
        String jobTitle = fieldTeacherJobTitle.getText();
        String subject = fieldTeacherSubject.getText();
        
        Teacher newTeacher = new Teacher(idNum, fullName, birthdate, gender, jobTitle, subject);
        Accounts.teachers.add(newTeacher);
    }//GEN-LAST:event_buttonTeacherRegisterActionPerformed

    private void comboTeacherGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTeacherGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTeacherGenderActionPerformed

    private void buttonRegistrarBackToUserListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarBackToUserListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRegistrarBackToUserListActionPerformed

    private void buttonRegistrarRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarRegisterActionPerformed
        String idNum = fieldRegistrarIdNum.getText();
        
        int genderIndex = comboRegistrarGender.getSelectedIndex();
        Gender gender = Gender.values()[genderIndex];        
        
        String firstName = fieldRegistrarFirstName.getText();
        String middleName = fieldRegistrarMiddleName.getText();
        String lastName = fieldRegistrarLastName.getText();
        FullName fullName = new FullName(firstName, middleName, lastName);
        
        int birthMonth = comboRegistrarMonth.getSelectedIndex();
        int birthDate = comboRegistrarDate.getSelectedIndex() + 1;
        int birthYear = comboRegistrarYear.getSelectedIndex() + 80;
        Date birthdate = new Date(birthYear, birthMonth, birthDate);
        
        String jobTitle = fieldRegistrarJobTitle.getText();
        
        Registrar newRegistrar = new Registrar(idNum, fullName, birthdate, gender, jobTitle);
        Accounts.registrars.add(newRegistrar);
    }//GEN-LAST:event_buttonRegistrarRegisterActionPerformed

    private void comboRegistrarGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRegistrarGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRegistrarGenderActionPerformed

    private void panelProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProfileMouseClicked
        this.setVisible(false);
        AdminWindowProfile awp = new AdminWindowProfile();
        awp.show();
        awp.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelProfileMouseClicked

    private void panelSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSubjectsMouseClicked
        this.setVisible(false);
        AdminWindowSubjects aws = new AdminWindowSubjects();
        aws.show();
        aws.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelSubjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindowRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindowRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindowRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindowRegisterUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindowRegisterUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdminBackToUserList;
    private javax.swing.JButton buttonAdminRegister;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonRegistrarBackToUserList;
    private javax.swing.JButton buttonRegistrarRegister;
    private javax.swing.JButton buttonStudentBackToUserList;
    private javax.swing.JButton buttonStudentRegister;
    private javax.swing.JButton buttonTeacherBackToUserList;
    private javax.swing.JButton buttonTeacherRegister;
    private javax.swing.JComboBox<String> comboAdminDate;
    private javax.swing.JComboBox<String> comboAdminGender;
    private javax.swing.JComboBox<String> comboAdminMonth;
    private javax.swing.JComboBox<String> comboAdminYear;
    private javax.swing.JComboBox<String> comboRegistrarDate;
    private javax.swing.JComboBox<String> comboRegistrarGender;
    private javax.swing.JComboBox<String> comboRegistrarMonth;
    private javax.swing.JComboBox<String> comboRegistrarYear;
    private javax.swing.JComboBox<String> comboStudentDate;
    private javax.swing.JComboBox<String> comboStudentGender;
    private javax.swing.JComboBox<String> comboStudentMonth;
    private javax.swing.JComboBox<String> comboStudentSection;
    private javax.swing.JComboBox<String> comboStudentYear;
    private javax.swing.JComboBox<String> comboTeacherDate;
    private javax.swing.JComboBox<String> comboTeacherGender;
    private javax.swing.JComboBox<String> comboTeacherMonth;
    private javax.swing.JComboBox<String> comboTeacherYear;
    private javax.swing.JTextField fieldAdminFirstName;
    private javax.swing.JTextField fieldAdminIdNum;
    private javax.swing.JTextField fieldAdminJobTitle;
    private javax.swing.JTextField fieldAdminLastName;
    private javax.swing.JTextField fieldAdminMiddleName;
    private javax.swing.JTextField fieldRegistrarFirstName;
    private javax.swing.JTextField fieldRegistrarIdNum;
    private javax.swing.JTextField fieldRegistrarJobTitle;
    private javax.swing.JTextField fieldRegistrarLastName;
    private javax.swing.JTextField fieldRegistrarMiddleName;
    private javax.swing.JTextField fieldStudentFirstName;
    private javax.swing.JTextField fieldStudentIdNum;
    private javax.swing.JTextField fieldStudentLastName;
    private javax.swing.JTextField fieldStudentMiddleName1;
    private javax.swing.JTextField fieldTeacherFirstName;
    private javax.swing.JTextField fieldTeacherIdNum;
    private javax.swing.JTextField fieldTeacherJobTitle;
    private javax.swing.JTextField fieldTeacherLastName;
    private javax.swing.JTextField fieldTeacherMiddleName;
    private javax.swing.JTextField fieldTeacherSubject;
    private javax.swing.JLabel headerAdminBirthdate;
    private javax.swing.JLabel headerAdminDate;
    private javax.swing.JLabel headerAdminFirstName;
    private javax.swing.JLabel headerAdminGender;
    private javax.swing.JLabel headerAdminIdNum;
    private javax.swing.JLabel headerAdminJobTitle;
    private javax.swing.JLabel headerAdminLastName;
    private javax.swing.JLabel headerAdminMiddleName;
    private javax.swing.JLabel headerAdminMonth;
    private javax.swing.JLabel headerAdminTitle;
    private javax.swing.JLabel headerAdminYear;
    private javax.swing.JLabel headerAdministrator;
    private javax.swing.JLabel headerProfile;
    private javax.swing.JLabel headerRegisterUser;
    private javax.swing.JLabel headerRegistrarBirthdate;
    private javax.swing.JLabel headerRegistrarDate;
    private javax.swing.JLabel headerRegistrarFirstName;
    private javax.swing.JLabel headerRegistrarGender;
    private javax.swing.JLabel headerRegistrarIdNum;
    private javax.swing.JLabel headerRegistrarJobTitle;
    private javax.swing.JLabel headerRegistrarLastName;
    private javax.swing.JLabel headerRegistrarMiddleName;
    private javax.swing.JLabel headerRegistrarMonth;
    private javax.swing.JLabel headerRegistrarTitle;
    private javax.swing.JLabel headerRegistrarYear;
    private javax.swing.JLabel headerStudentBirthdate;
    private javax.swing.JLabel headerStudentDate;
    private javax.swing.JLabel headerStudentFirstName;
    private javax.swing.JLabel headerStudentGender;
    private javax.swing.JLabel headerStudentIdNum;
    private javax.swing.JLabel headerStudentLastName;
    private javax.swing.JLabel headerStudentMiddleName;
    private javax.swing.JLabel headerStudentMonth;
    private javax.swing.JLabel headerStudentSection;
    private javax.swing.JLabel headerStudentTitle;
    private javax.swing.JLabel headerStudentYear;
    private javax.swing.JLabel headerSubjects;
    private javax.swing.JLabel headerTeacherBirthdate;
    private javax.swing.JLabel headerTeacherDate;
    private javax.swing.JLabel headerTeacherFirstName;
    private javax.swing.JLabel headerTeacherGender;
    private javax.swing.JLabel headerTeacherIdNum;
    private javax.swing.JLabel headerTeacherJobTitle;
    private javax.swing.JLabel headerTeacherLastName;
    private javax.swing.JLabel headerTeacherMiddleName;
    private javax.swing.JLabel headerTeacherMonth;
    private javax.swing.JLabel headerTeacherSubject;
    private javax.swing.JLabel headerTeacherTitle;
    private javax.swing.JLabel headerTeacherYear;
    private javax.swing.JLabel headerUsersList;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelRegisterAdmin;
    private javax.swing.JPanel panelRegisterRegistrar;
    private javax.swing.JPanel panelRegisterStudent;
    private javax.swing.JPanel panelRegisterTeacher;
    private javax.swing.JPanel panelRegisterUser;
    private javax.swing.JPanel panelSubjects;
    private javax.swing.JPanel panelUsersList;
    private javax.swing.JTabbedPane tabPane;
    // End of variables declaration//GEN-END:variables
}
