/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.abadier.enrolmentsystem;

import java.util.Date;

/**
 *
 * @author ron.g.abadier
 */
public class AdminSignUp extends javax.swing.JFrame {

    /**
     * Creates new form AdminSignUp
     */
    public AdminSignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerYear = new javax.swing.JLabel();
        headerLastName = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        buttonSubmit = new javax.swing.JButton();
        buttonBackToLogin = new javax.swing.JButton();
        fieldLastName = new javax.swing.JTextField();
        headerIdNum = new javax.swing.JLabel();
        headerBirthdate = new javax.swing.JLabel();
        fieldIdNum = new javax.swing.JTextField();
        headerMonth = new javax.swing.JLabel();
        headerGender = new javax.swing.JLabel();
        comboMonth = new javax.swing.JComboBox<>();
        comboGender = new javax.swing.JComboBox<>();
        comboYear = new javax.swing.JComboBox<>();
        headerDate = new javax.swing.JLabel();
        headerMiddleName = new javax.swing.JLabel();
        headerTitle = new javax.swing.JLabel();
        headerJobTitle = new javax.swing.JLabel();
        comboDate = new javax.swing.JComboBox<>();
        fieldMiddleName = new javax.swing.JTextField();
        headerFirstName = new javax.swing.JLabel();
        fieldJobTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headerYear.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        headerYear.setText("YYYY");

        headerLastName.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerLastName.setText("Last Name");

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });

        buttonSubmit.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonSubmit.setText("Submit");
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });

        buttonBackToLogin.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonBackToLogin.setText("Back");
        buttonBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackToLoginActionPerformed(evt);
            }
        });

        fieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldLastNameActionPerformed(evt);
            }
        });

        headerIdNum.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerIdNum.setText("ID Number");

        headerBirthdate.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerBirthdate.setText("Birthdate");

        fieldIdNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIdNumActionPerformed(evt);
            }
        });

        headerMonth.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        headerMonth.setText("MM");

        headerGender.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerGender.setText("Gender");

        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        comboGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboGenderActionPerformed(evt);
            }
        });

        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        headerDate.setFont(new java.awt.Font("Yu Gothic", 2, 14)); // NOI18N
        headerDate.setText("DD");

        headerMiddleName.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerMiddleName.setText("Middle Name");

        headerTitle.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        headerTitle.setText("ADMINISTRATOR REGISTRATION FORM");

        headerJobTitle.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerJobTitle.setText("Job Title");

        comboDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        comboDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDateActionPerformed(evt);
            }
        });

        fieldMiddleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMiddleNameActionPerformed(evt);
            }
        });

        headerFirstName.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        headerFirstName.setText("First Name");

        fieldJobTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJobTitleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(headerJobTitle)
                                .addGap(18, 18, 18)
                                .addComponent(fieldJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(headerBirthdate)
                                .addGap(18, 18, 18)
                                .addComponent(headerMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(headerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(headerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(headerIdNum)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(headerGender)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(headerFirstName)
                                        .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerMiddleName)
                                        .addComponent(fieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(headerLastName)))))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonBackToLogin)
                        .addGap(83, 83, 83)
                        .addComponent(buttonSubmit)
                        .addGap(153, 153, 153))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(headerTitle)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(headerTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerIdNum)
                    .addComponent(headerGender)
                    .addComponent(fieldIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerFirstName)
                            .addComponent(headerLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerMiddleName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerBirthdate)
                    .addComponent(headerMonth)
                    .addComponent(comboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerDate)
                    .addComponent(comboDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerYear)
                    .addComponent(comboYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerJobTitle)
                    .addComponent(fieldJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBackToLogin)
                    .addComponent(buttonSubmit))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        String idNum = fieldIdNum.getText();
        
        int genderIndex = comboGender.getSelectedIndex();
        Gender gender = Gender.values()[genderIndex];        
        
        String firstName = fieldFirstName.getText();
        String middleName = fieldMiddleName.getText();
        String lastName = fieldLastName.getText();
        FullName fullName = new FullName(firstName, middleName, lastName);
        
        int birthMonth = comboMonth.getSelectedIndex();
        int birthDate = comboDate.getSelectedIndex() + 1;
        int birthYear = comboYear.getSelectedIndex() + 80;
        Date birthdate = new Date(birthYear, birthMonth, birthDate);
        
        String jobTitle = fieldJobTitle.getSelectedText();
        
        Administrator newAdmin = new Administrator(idNum, fullName, birthdate, gender, jobTitle);
        Accounts.admins.add(newAdmin);
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackToLoginActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.show();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonBackToLoginActionPerformed

    private void fieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldLastNameActionPerformed

    private void fieldIdNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIdNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIdNumActionPerformed

    private void comboGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboGenderActionPerformed

    private void comboDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDateActionPerformed

    private void fieldMiddleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMiddleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMiddleNameActionPerformed

    private void fieldJobTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJobTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJobTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBackToLogin;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JComboBox<String> comboDate;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldIdNum;
    private javax.swing.JTextField fieldJobTitle;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldMiddleName;
    private javax.swing.JLabel headerBirthdate;
    private javax.swing.JLabel headerDate;
    private javax.swing.JLabel headerFirstName;
    private javax.swing.JLabel headerGender;
    private javax.swing.JLabel headerIdNum;
    private javax.swing.JLabel headerJobTitle;
    private javax.swing.JLabel headerLastName;
    private javax.swing.JLabel headerMiddleName;
    private javax.swing.JLabel headerMonth;
    private javax.swing.JLabel headerTitle;
    private javax.swing.JLabel headerYear;
    // End of variables declaration//GEN-END:variables
}
