/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.abadier.enrolmentsystem;

import java.util.Date;
import java.util.LinkedList;

/**
 *
 * @author ron.g.abadier
 */
public class AdminWindowProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindowProfile
     */
    public AdminWindowProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        textUser = new javax.swing.JLabel();
        panelUsersList = new javax.swing.JPanel();
        headerUsersList = new javax.swing.JLabel();
        panelRegister = new javax.swing.JPanel();
        headerRegister = new javax.swing.JLabel();
        panelProfile = new javax.swing.JPanel();
        headerProfile = new javax.swing.JLabel();
        panelSubjects = new javax.swing.JPanel();
        headerSubjects = new javax.swing.JLabel();
        panelUpdate = new javax.swing.JPanel();
        headerAdminYear = new javax.swing.JLabel();
        headerAdminGender = new javax.swing.JLabel();
        comboAdminMonth = new javax.swing.JComboBox<>();
        headerAdminBirthdate = new javax.swing.JLabel();
        headerAdminMonth = new javax.swing.JLabel();
        headerAdminMiddleName = new javax.swing.JLabel();
        headerAdminLastName = new javax.swing.JLabel();
        fieldAdminMiddleName = new javax.swing.JTextField();
        buttonAdminUpdate = new javax.swing.JButton();
        fieldAdminLastName = new javax.swing.JTextField();
        fieldAdminFirstName = new javax.swing.JTextField();
        fieldAdminIdNum = new javax.swing.JTextField();
        headerAdminJobTitle = new javax.swing.JLabel();
        headerAdminFirstName = new javax.swing.JLabel();
        comboAdminYear = new javax.swing.JComboBox<>();
        headerAdminIdNum = new javax.swing.JLabel();
        headerAdminTitle = new javax.swing.JLabel();
        comboAdminDate = new javax.swing.JComboBox<>();
        comboAdminGender = new javax.swing.JComboBox<>();
        headerAdminDate = new javax.swing.JLabel();
        fieldAdminJobTitle = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        buttonLogout.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(null);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        textUser.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        textUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUser.setText("ADMINISTRATOR");
        textUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelUsersList.setBackground(new java.awt.Color(224, 224, 224));
        panelUsersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUsersListMouseClicked(evt);
            }
        });

        headerUsersList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUsersList.setText("Users List");

        javax.swing.GroupLayout panelUsersListLayout = new javax.swing.GroupLayout(panelUsersList);
        panelUsersList.setLayout(panelUsersListLayout);
        panelUsersListLayout.setHorizontalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerUsersList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersListLayout.setVerticalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersListLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerUsersList)
                .addContainerGap())
        );

        panelRegister.setBackground(new java.awt.Color(224, 224, 224));
        panelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRegisterMouseClicked(evt);
            }
        });

        headerRegister.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerRegister.setText("Register");

        javax.swing.GroupLayout panelRegisterLayout = new javax.swing.GroupLayout(panelRegister);
        panelRegister.setLayout(panelRegisterLayout);
        panelRegisterLayout.setHorizontalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegisterLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerRegister)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRegisterLayout.setVerticalGroup(
            panelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegisterLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerRegister)
                .addContainerGap())
        );

        panelProfile.setBackground(new java.awt.Color(224, 224, 224));
        panelProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProfileMouseClicked(evt);
            }
        });

        headerProfile.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerProfile.setText("Profile");

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerProfile)
                .addContainerGap())
        );

        panelSubjects.setBackground(new java.awt.Color(224, 224, 224));
        panelSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSubjectsMouseClicked(evt);
            }
        });

        headerSubjects.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjects.setText("Subjects");

        javax.swing.GroupLayout panelSubjectsLayout = new javax.swing.GroupLayout(panelSubjects);
        panelSubjects.setLayout(panelSubjectsLayout);
        panelSubjectsLayout.setHorizontalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerSubjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubjectsLayout.setVerticalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerSubjects)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(panelRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubjects, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(textUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelUpdate.setBackground(new java.awt.Color(255, 255, 255));

        headerAdminYear.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerAdminYear.setText("YYYY");

        headerAdminGender.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminGender.setText("Gender");
        headerAdminGender.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboAdminMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        headerAdminBirthdate.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminBirthdate.setText("Birthdate");
        headerAdminBirthdate.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminMonth.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerAdminMonth.setText("MM");

        headerAdminMiddleName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminMiddleName.setText("Middle name");
        headerAdminMiddleName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminLastName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminLastName.setText("Last name");
        headerAdminLastName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        buttonAdminUpdate.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonAdminUpdate.setText("Update");
        buttonAdminUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminUpdateActionPerformed(evt);
            }
        });

        headerAdminJobTitle.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminJobTitle.setText("Title");
        headerAdminJobTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminFirstName.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminFirstName.setText("First name");
        headerAdminFirstName.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        comboAdminYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));

        headerAdminIdNum.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerAdminIdNum.setText("ID number");
        headerAdminIdNum.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        headerAdminTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerAdminTitle.setText("PROFILE");

        comboAdminDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        comboAdminGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        comboAdminGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAdminGenderActionPerformed(evt);
            }
        });

        headerAdminDate.setFont(new java.awt.Font("Yu Gothic", 2, 12)); // NOI18N
        headerAdminDate.setText("DD");

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(headerAdminIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldAdminIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(headerAdminGender, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(comboAdminGender, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUpdateLayout.createSequentialGroup()
                                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerAdminMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAdminMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(headerAdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(headerAdminBirthdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelUpdateLayout.createSequentialGroup()
                                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(headerAdminJobTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(headerAdminMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldAdminJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelUpdateLayout.createSequentialGroup()
                                            .addComponent(comboAdminMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(headerAdminDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(comboAdminDate, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(headerAdminYear, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(comboAdminYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(headerAdminTitle)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonAdminUpdate)
                .addGap(41, 41, 41))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headerAdminTitle)
                .addGap(28, 28, 28)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminIdNum)
                    .addComponent(fieldAdminIdNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerAdminGender)
                    .addComponent(comboAdminGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminFirstName)
                    .addComponent(headerAdminLastName)
                    .addComponent(headerAdminMiddleName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldAdminMiddleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(headerAdminBirthdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminMonth)
                    .addComponent(comboAdminMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerAdminDate)
                    .addComponent(comboAdminDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerAdminYear)
                    .addComponent(comboAdminYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(headerAdminJobTitle)
                    .addComponent(fieldAdminJobTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(buttonAdminUpdate)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.show();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void panelUsersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsersListMouseClicked
        this.setVisible(false);
        AdminWindowUserList awul = new AdminWindowUserList();
        awul.show();
        awul.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelUsersListMouseClicked

    private void panelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRegisterMouseClicked
        this.setVisible(false);
        AdminWindowRegisterUser awru = new AdminWindowRegisterUser();
        awru.show();
        awru.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelRegisterMouseClicked

    private void panelProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProfileMouseClicked
        this.setVisible(false);
        AdminWindowProfile awp = new AdminWindowProfile();
        awp.show();
        awp.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelProfileMouseClicked

    private void comboAdminGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAdminGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAdminGenderActionPerformed

    private void buttonAdminUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminUpdateActionPerformed
        String idNum = fieldAdminIdNum.getText();
        
        int genderIndex = comboAdminGender.getSelectedIndex();
        Gender gender = Gender.values()[genderIndex];        
        
        String firstName = fieldAdminFirstName.getText();
        String middleName = fieldAdminMiddleName.getText();
        String lastName = fieldAdminLastName.getText();
        FullName fullName = new FullName(firstName, middleName, lastName);
        
        int birthMonth = comboAdminMonth.getSelectedIndex();
        int birthDate = comboAdminDate.getSelectedIndex() + 1;
        int birthYear = comboAdminYear.getSelectedIndex() + 80;
        Date birthdate = new Date(birthYear, birthMonth, birthDate);
        
        String jobTitle = fieldAdminJobTitle.getText();
        
        if (idNum.equals("") || firstName.equals("") || middleName.equals("") || lastName.equals("") || jobTitle.equals("")) {
            javax.swing.JFrame failedUpdate = new javax.swing.JFrame();
            javax.swing.JOptionPane.showMessageDialog(failedUpdate, "You have a blank field! Please fill up all fields.");
        } else {
            Administrator admin = new Administrator(idNum, fullName, birthdate, gender, jobTitle);
            admin.editAdmin(idNum, firstName, middleName, lastName, birthdate, gender, jobTitle);
            javax.swing.JFrame successfulUpdate = new javax.swing.JFrame();
            javax.swing.JOptionPane.showMessageDialog(successfulUpdate, "You have successfully updated your profile!");
        }
    }//GEN-LAST:event_buttonAdminUpdateActionPerformed

    private void panelSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSubjectsMouseClicked
        this.setVisible(false);
        AdminWindowSubjects aws = new AdminWindowSubjects();
        aws.show();
        aws.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelSubjectsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindowProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindowProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdminUpdate;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JComboBox<String> comboAdminDate;
    private javax.swing.JComboBox<String> comboAdminGender;
    private javax.swing.JComboBox<String> comboAdminMonth;
    private javax.swing.JComboBox<String> comboAdminYear;
    private javax.swing.JTextField fieldAdminFirstName;
    private javax.swing.JTextField fieldAdminIdNum;
    private javax.swing.JTextField fieldAdminJobTitle;
    private javax.swing.JTextField fieldAdminLastName;
    private javax.swing.JTextField fieldAdminMiddleName;
    private javax.swing.JLabel headerAdminBirthdate;
    private javax.swing.JLabel headerAdminDate;
    private javax.swing.JLabel headerAdminFirstName;
    private javax.swing.JLabel headerAdminGender;
    private javax.swing.JLabel headerAdminIdNum;
    private javax.swing.JLabel headerAdminJobTitle;
    private javax.swing.JLabel headerAdminLastName;
    private javax.swing.JLabel headerAdminMiddleName;
    private javax.swing.JLabel headerAdminMonth;
    private javax.swing.JLabel headerAdminTitle;
    private javax.swing.JLabel headerAdminYear;
    private javax.swing.JLabel headerProfile;
    private javax.swing.JLabel headerRegister;
    private javax.swing.JLabel headerSubjects;
    private javax.swing.JLabel headerUsersList;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelRegister;
    private javax.swing.JPanel panelSubjects;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelUsersList;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
