/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.abadier.enrolmentsystem;

import static edu.abadier.enrolmentsystem.Subjects.subjects;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ron.g.abadier
 */
public class RegistrarWindowSubjects extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindowSubjects
     */
    public RegistrarWindowSubjects() {
        initComponents();
        SetTableView();
        AddColumnListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        buttonLogout = new javax.swing.JButton();
        textUser = new javax.swing.JLabel();
        panelUsersList = new javax.swing.JPanel();
        headerUsersList = new javax.swing.JLabel();
        panelSubjects = new javax.swing.JPanel();
        headerSubjects = new javax.swing.JLabel();
        panelProfile = new javax.swing.JPanel();
        headerProfile = new javax.swing.JLabel();
        tabPane = new javax.swing.JTabbedPane();
        panelSubjectList = new javax.swing.JPanel();
        buttonSearch = new javax.swing.JButton();
        scrollSubjectList = new javax.swing.JScrollPane();
        tableSubjectList = new javax.swing.JTable();
        headerSubjectTitle = new javax.swing.JLabel();
        fieldSubjectSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        buttonLogout.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(null);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        textUser.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        textUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUser.setText("REGISTRAR");
        textUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        panelUsersList.setBackground(new java.awt.Color(224, 224, 224));
        panelUsersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUsersListMouseClicked(evt);
            }
        });

        headerUsersList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUsersList.setText("Users List");

        javax.swing.GroupLayout panelUsersListLayout = new javax.swing.GroupLayout(panelUsersList);
        panelUsersList.setLayout(panelUsersListLayout);
        panelUsersListLayout.setHorizontalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerUsersList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersListLayout.setVerticalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersListLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerUsersList)
                .addContainerGap())
        );

        panelSubjects.setBackground(new java.awt.Color(224, 224, 224));
        panelSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSubjectsMouseClicked(evt);
            }
        });

        headerSubjects.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjects.setText("Subjects");

        javax.swing.GroupLayout panelSubjectsLayout = new javax.swing.GroupLayout(panelSubjects);
        panelSubjects.setLayout(panelSubjectsLayout);
        panelSubjectsLayout.setHorizontalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerSubjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubjectsLayout.setVerticalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerSubjects)
                .addContainerGap())
        );

        panelProfile.setBackground(new java.awt.Color(224, 224, 224));
        panelProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProfileMouseClicked(evt);
            }
        });

        headerProfile.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerProfile.setText("Profile");

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerProfile)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(panelUsersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(textUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelSubjectList.setBackground(new java.awt.Color(255, 255, 255));

        buttonSearch.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        tableSubjectList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tableSubjectList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Subject", "Teacher"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableSubjectList.getTableHeader().setReorderingAllowed(false);
        scrollSubjectList.setViewportView(tableSubjectList);
        if (tableSubjectList.getColumnModel().getColumnCount() > 0) {
            tableSubjectList.getColumnModel().getColumn(0).setResizable(false);
            tableSubjectList.getColumnModel().getColumn(1).setResizable(false);
            tableSubjectList.getColumnModel().getColumn(2).setResizable(false);
        }

        headerSubjectTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerSubjectTitle.setText("SUBJECT LIST");

        fieldSubjectSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSubjectSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSubjectListLayout = new javax.swing.GroupLayout(panelSubjectList);
        panelSubjectList.setLayout(panelSubjectListLayout);
        panelSubjectListLayout.setHorizontalGroup(
            panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectListLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSubjectListLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectListLayout.createSequentialGroup()
                                .addComponent(fieldSubjectSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonSearch))
                            .addComponent(scrollSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(headerSubjectTitle))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        panelSubjectListLayout.setVerticalGroup(
            panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectListLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(headerSubjectTitle)
                .addGap(18, 18, 18)
                .addGroup(panelSubjectListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSearch)
                    .addComponent(fieldSubjectSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollSubjectList, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        tabPane.addTab("View", panelSubjectList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.show();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void panelUsersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsersListMouseClicked
        this.setVisible(false);
        RegistrarWindowUserList rwul = new RegistrarWindowUserList();
        rwul.show();
        rwul.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelUsersListMouseClicked

    private void panelSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSubjectsMouseClicked
        this.setVisible(false);
        RegistrarWindowSubjects rws = new RegistrarWindowSubjects();
        rws.show();
        rws.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelSubjectsMouseClicked

    private void panelProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProfileMouseClicked
        this.setVisible(false);
        RegistrarWindowProfile rwp = new RegistrarWindowProfile();
        rwp.show();
        rwp.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelProfileMouseClicked

    private void fieldSubjectSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSubjectSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSubjectSearchActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarWindowSubjects.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarWindowSubjects().setVisible(true);
            }
        });
    }
    
        void SetTableView() {
        DefaultTableModel subjectList = (DefaultTableModel) tableSubjectList.getModel();
        subjectList.setRowCount(0);
        
        for (int i = 0; i < subjects.size(); i++){
            String code = subjects.get(i).getSubjectCode();
            String name = subjects.get(i).getSubjectName();
            String teacher = subjects.get(i).getSubjectTeacher();
            
            Object[] row = {code, name, teacher};
            subjectList.addRow(row);
        }
    }
    
    void AddColumnListener() {
        JTableHeader header = tableSubjectList.getTableHeader();
        header.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                int columnIndex = header.columnAtPoint(e.getPoint());
                System.out.println("Column " + columnIndex + " is clicked.");
                
                switch(columnIndex){
                    case 0 -> {
                        subjects = Subjects.sortCode(subjects, descending);
                        descending = !descending;
                    }
                    case 1 -> {
                        subjects = Subjects.sortName(subjects, descending);
                        descending = !descending;
                    }
                    case 2 -> {
                        subjects = Subjects.sortTeacher(subjects, descending);
                        descending = !descending;
                    }
                }
                SetTableView();
            }
        });
    }

    private boolean descending = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JTextField fieldSubjectSearch;
    private javax.swing.JLabel headerProfile;
    private javax.swing.JLabel headerSubjectTitle;
    private javax.swing.JLabel headerSubjects;
    private javax.swing.JLabel headerUsersList;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelSubjectList;
    private javax.swing.JPanel panelSubjects;
    private javax.swing.JPanel panelUsersList;
    private javax.swing.JScrollPane scrollSubjectList;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tableSubjectList;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
