/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.abadier.enrolmentsystem;

import static edu.abadier.enrolmentsystem.Accounts.students;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author ron.g.abadier
 */
public class TeacherWindowUserList extends javax.swing.JFrame {

    /**
     * Creates new form AdminWindowUserList
     */
    public TeacherWindowUserList() {
        initComponents();
        SetTableView();
        AddColumnListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        textUser = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        panelUsersList = new javax.swing.JPanel();
        headerUsersList = new javax.swing.JLabel();
        panelSubjects = new javax.swing.JPanel();
        headerSubjects = new javax.swing.JLabel();
        panelProfile = new javax.swing.JPanel();
        headerProfile = new javax.swing.JLabel();
        tabPaneUsersList = new javax.swing.JTabbedPane();
        panelStudents = new javax.swing.JPanel();
        headerStudentsTitle = new javax.swing.JLabel();
        fieldStudentsSearch = new javax.swing.JTextField();
        buttonStudentsSearch = new javax.swing.JButton();
        scrollStudentsUserList = new javax.swing.JScrollPane();
        tableStudentList = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("User List");
        setLocation(new java.awt.Point(300, 150));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setResizable(false);

        panelMenu.setBackground(new java.awt.Color(204, 204, 204));

        textUser.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        textUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textUser.setText("TEACHER");
        textUser.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        buttonLogout.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(null);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        panelUsersList.setBackground(new java.awt.Color(224, 224, 224));
        panelUsersList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelUsersListMouseClicked(evt);
            }
        });

        headerUsersList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerUsersList.setText("Users List");

        javax.swing.GroupLayout panelUsersListLayout = new javax.swing.GroupLayout(panelUsersList);
        panelUsersList.setLayout(panelUsersListLayout);
        panelUsersListLayout.setHorizontalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersListLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerUsersList)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersListLayout.setVerticalGroup(
            panelUsersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUsersListLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerUsersList)
                .addContainerGap())
        );

        panelSubjects.setBackground(new java.awt.Color(224, 224, 224));
        panelSubjects.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelSubjectsMouseClicked(evt);
            }
        });

        headerSubjects.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerSubjects.setText("Subjects");

        javax.swing.GroupLayout panelSubjectsLayout = new javax.swing.GroupLayout(panelSubjects);
        panelSubjects.setLayout(panelSubjectsLayout);
        panelSubjectsLayout.setHorizontalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSubjectsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerSubjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSubjectsLayout.setVerticalGroup(
            panelSubjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSubjectsLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerSubjects)
                .addContainerGap())
        );

        panelProfile.setBackground(new java.awt.Color(224, 224, 224));
        panelProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelProfileMouseClicked(evt);
            }
        });

        headerProfile.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        headerProfile.setText("Profile");

        javax.swing.GroupLayout panelProfileLayout = new javax.swing.GroupLayout(panelProfile);
        panelProfile.setLayout(panelProfileLayout);
        panelProfileLayout.setHorizontalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfileLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(headerProfile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfileLayout.setVerticalGroup(
            panelProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProfileLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(headerProfile)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addComponent(panelUsersList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelSubjects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(textUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSubjects, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tabPaneUsersList.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabPaneUsersListFocusGained(evt);
            }
        });
        tabPaneUsersList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabPaneUsersListPropertyChange(evt);
            }
        });

        panelStudents.setBackground(new java.awt.Color(255, 255, 255));

        headerStudentsTitle.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        headerStudentsTitle.setText("STUDENTS LIST");

        fieldStudentsSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldStudentsSearchActionPerformed(evt);
            }
        });

        buttonStudentsSearch.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        buttonStudentsSearch.setText("Search");
        buttonStudentsSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentsSearchActionPerformed(evt);
            }
        });

        tableStudentList.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        tableStudentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID #", "Last Name", "First Name", "Middle Name", "Birthdate", "Gender", "Year Level", "Section"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableStudentList.getTableHeader().setReorderingAllowed(false);
        scrollStudentsUserList.setViewportView(tableStudentList);
        if (tableStudentList.getColumnModel().getColumnCount() > 0) {
            tableStudentList.getColumnModel().getColumn(0).setResizable(false);
            tableStudentList.getColumnModel().getColumn(0).setPreferredWidth(50);
            tableStudentList.getColumnModel().getColumn(1).setResizable(false);
            tableStudentList.getColumnModel().getColumn(2).setResizable(false);
            tableStudentList.getColumnModel().getColumn(3).setResizable(false);
            tableStudentList.getColumnModel().getColumn(4).setResizable(false);
            tableStudentList.getColumnModel().getColumn(5).setResizable(false);
            tableStudentList.getColumnModel().getColumn(5).setPreferredWidth(50);
            tableStudentList.getColumnModel().getColumn(6).setResizable(false);
            tableStudentList.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout panelStudentsLayout = new javax.swing.GroupLayout(panelStudents);
        panelStudents.setLayout(panelStudentsLayout);
        panelStudentsLayout.setHorizontalGroup(
            panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrollStudentsUserList)
                        .addGroup(panelStudentsLayout.createSequentialGroup()
                            .addComponent(fieldStudentsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(buttonStudentsSearch)))
                    .addComponent(headerStudentsTitle))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelStudentsLayout.setVerticalGroup(
            panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(headerStudentsTitle)
                .addGap(18, 18, 18)
                .addGroup(panelStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStudentsSearch)
                    .addComponent(fieldStudentsSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollStudentsUserList, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        tabPaneUsersList.addTab("Students", panelStudents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneUsersList))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabPaneUsersList)
        );

        tabPaneUsersList.getAccessibleContext().setAccessibleName("Users");

        getAccessibleContext().setAccessibleName("adminWindowUserList");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed
        this.setVisible(false);
        Login l = new Login();
        l.show();
        l.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void tabPaneUsersListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabPaneUsersListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tabPaneUsersListPropertyChange

    private void tabPaneUsersListFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabPaneUsersListFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tabPaneUsersListFocusGained

    private void buttonStudentsSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentsSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStudentsSearchActionPerformed

    private void fieldStudentsSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldStudentsSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldStudentsSearchActionPerformed

    private void panelUsersListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUsersListMouseClicked
        this.setVisible(false);
        TeacherWindowUserList twul = new TeacherWindowUserList();
        twul.show();
        twul.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelUsersListMouseClicked

    private void panelSubjectsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelSubjectsMouseClicked
        this.setVisible(false);
        TeacherWindowSubjects tws = new TeacherWindowSubjects();
        tws.show();
        tws.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelSubjectsMouseClicked

    private void panelProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelProfileMouseClicked
        this.setVisible(false);
        TeacherWindowProfile twp = new TeacherWindowProfile();
        twp.show();
        twp.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_panelProfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherWindowUserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherWindowUserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherWindowUserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherWindowUserList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherWindowUserList().setVisible(true);
            }
        });
    }
    
    void SetTableView() {
        DefaultTableModel studentList = (DefaultTableModel) tableStudentList.getModel();
        studentList.setRowCount(0);
        
        for (int i = 0; i < students.size(); i++){
            String idNum = students.get(i).getIdNum();
            String lastName = students.get(i).getFullName().getLastName();
            String firstName = students.get(i).getFullName().getFirstName();
            String middleName = students.get(i).getFullName().getMiddleName();
            Date birthdate = students.get(i).getBirthdate();
            Gender gender = students.get(i).getGender();
            int yearLevel = students.get(i).getYearLevel();
            Section section = students.get(i).getSection();
            
            Object[] row = {idNum, lastName, firstName, middleName, birthdate, gender, yearLevel, section};
            studentList.addRow(row);
        }
    }
    
    void AddColumnListener() {
        JTableHeader studentHeader = tableStudentList.getTableHeader();
        studentHeader.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                int columnIndex = studentHeader.columnAtPoint(e.getPoint());
                System.out.println("Column " + columnIndex + " is clicked.");
                
                switch(columnIndex){
                    case 0 -> {
                        students = Accounts.sortStudentIdNum(students, descending);
                        descending = !descending;
                    }
                    case 1 -> {
                        students = Accounts.sortStudentLastName(students, descending);
                        descending = !descending;
                    }
                    case 2 -> {
                        students = Accounts.sortStudentFirstName(students, descending);
                        descending = !descending;
                    }
                    case 3 -> {
                        students = Accounts.sortStudentMiddleName(students, descending);
                        descending = !descending;
                    }
                    case 5 -> {
                        students = Accounts.sortStudentGender(students, descending);
                        descending = !descending;
                    }
                    case 6 -> {
                        students = Accounts.sortStudentYearLevel(students, descending);
                        descending = !descending;
                    }
                    case 7 -> {
                        students = Accounts.sortStudentSection(students, descending);
                        descending = !descending;
                    }
                }
                SetTableView();
            }
        });
    }
    
    private boolean descending = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonStudentsSearch;
    private javax.swing.JTextField fieldStudentsSearch;
    private javax.swing.JLabel headerProfile;
    private javax.swing.JLabel headerStudentsTitle;
    private javax.swing.JLabel headerSubjects;
    private javax.swing.JLabel headerUsersList;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelProfile;
    private javax.swing.JPanel panelStudents;
    private javax.swing.JPanel panelSubjects;
    private javax.swing.JPanel panelUsersList;
    private javax.swing.JScrollPane scrollStudentsUserList;
    private javax.swing.JTabbedPane tabPaneUsersList;
    private javax.swing.JTable tableStudentList;
    private javax.swing.JLabel textUser;
    // End of variables declaration//GEN-END:variables
}
